### ISSUE TITLE
Lack of colorama hard dependency

### ISSUE THREAD

**Issue by SantiagoTorres** [secure-systems-lab/securesystemslib#153]
**Description of issue or feature request**:
The current release blows up because `colorama` is not a dependency. Although it *should* get pulled in by either `cryptography` or `pynacl`, there is no information to describe that is the issue when using securesystemslib.

For example, this is the test log from `in-toto` using the latest securesystemslib (given that it doesn't hard depend on either library)

```
======================================================================
ERROR: tests.test_runlib (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.test_runlib
Traceback (most recent call last):
  File "/usr/lib64/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib64/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/santiago/Documents/personal/programas/in-toto/in-toto/tests/test_runlib.py", line 29, in <module>
    from in_toto.models.metadata import Metablock
  File "/home/santiago/Documents/personal/programas/in-toto/in-toto/in_toto/models/metadata.py", line 34, in <module>
    from in_toto.models.layout import Layout
  File "/home/santiago/Documents/personal/programas/in-toto/in-toto/in_toto/models/layout.py", line 49, in <module>
    import securesystemslib.interface
  File "/home/santiago/Documents/personal/programas/in-toto/in-toto/.tox/py36/lib/python3.6/site-packages/securesystemslib/interface.py", line 51, in <module>
    from colorama import Fore
ModuleNotFoundError: No module named 'colorama'
```

Needless to say, it's rather dangerous to assume that `cryptography` or `pynacl` will depend on colorama forever. Worse than that, I'm assuming that we may add support for other libraries which may or may not pull `colorama` in.

**Current behavior**:
Thing breaks unless you explicitly:

1. Install a dependency that pulls `colorama`, such as `pynacl` or `cryptography`.
2. Install colorama explicitly to compensate for this lack of hard-dependency

**Expected behavior**:
The library installs itself with everything it needs and doesn't make any assumptions of the packages that will be pulled and their upstream dependencies.

**Comment by vladimir-v-diaz** [comment]
`cryptography`, `pynacl`, and `colorama` are now "extras" in setup.py.
https://github.com/secure-systems-lab/securesystemslib/blob/509a1860a54019cb82ec374dc1cd1487c34517ba/setup.py#L100-L101

I don't think the `cryptography` and `pynacl` projects actually depend on colorama.  It just appears that way when using the "extras" feature.  You can install the extras from requirements.txt with a `securesystemslib[crypto,pynacl]==0.11.2`  [Here](https://github.com/theupdateframework/tuf/blob/c8fcab9d1906d1784c52c723f4d5fa30a59e02a8/dev-requirements.txt#L32)'s how we install them in TUF.

Yash updated in-toto to use the new form, in both [setup.py](https://github.com/in-toto/in-toto/blob/8eb8eab8c94f47e67a24b5e7d56f4519092dd9d2/setup.py#L73-L74) and [requirements.txt](https://github.com/in-toto/in-toto/blob/develop/requirements.txt#L1).

The [SSLib installation instructions](https://github.com/secure-systems-lab/securesystemslib#installation) were also updated to note the extras.  If you want to install them from the current working directory, the commands would be:
```
# a default installation, which can only verify Ed25529 keys in pure python.
$ pip install .

# install/support cryptography and colorama
$ pip install .[crypto]

# install/support pynacl
$ pip install .[pynacl]
```

**Comment by SantiagoTorres** [comment]
> cryptography, pynacl, and colorama are now "extras" in setup.py.

I know, but that's not what an *extra* means

> Sometimes a project has “recommended” dependencies, that are not required for all uses of the project.

This reads as "you're holding it wrong". I'm sorry, but a default installation should have the minimum working set of packages, or be smart enough to tell there's a problem and extras are missing, not just blindly blowing up.

**Comment by vladimir-v-diaz** [comment]
I can add a better message to direct users to the installation instructions if they try to use a function that requires a specific library.

One of our adopters wanted to use SSLib without requiring C extensions.  I rather support requests from our users, even if the installation requires the "extras" features and isn't ideal.

**Comment by SantiagoTorres** [comment]
Colorama doesn't require C extensions, and a sensible error message/soft fail is what should happen. 

This code is trying to import a library that may or may not exist, due to your assumptions, so it should handle it properly.
