### ISSUE TITLE
Boundary between securesystemslib and TUF is off.

### ISSUE THREAD

**Issue by awwad** [secure-systems-lab/securesystemslib#161]
Some of the functions in securesystemslib are really pieces of TUF that I don't think are of use to others and don't belong here.

Some examples that IIUC don't belong in securesystemslib:
- util.ensure_all_targets_allowed(rolename, list_of_targets, parent_delegations)
- util.find_delegated_role(roles, delegated_role)
- formats.NUMBINS_SCHEMA
- formats.TARGETS_SCHEMA
- formats.SNAPSHOT_SCHEMA
- formats.TIMESTAMP_SCHEMA
- formats.ROOT_SCHEMA
- formats.MIRRORDICT_SCHEMA
- formats.MIRRORLIST_SCHEMA

Other functions that could conceivably be useful in general have zero context within the module:
- util.paths_are_consistent_with_hash_prefixes(paths, path_hash_prefixes)
- formats.PROJECT_CFG_SCHEMA

Things I'm less sure about:
- formats.THRESHOLD_SCHEMA
- exceptions.RoleAlreadyExistsError
- exceptions.UnknownRoleError
- formats.ROLENAME_SCHEMA

**Comment by JustinCappos** [comment]
The general concept makes sense to me.

**Comment by lukpueh** [comment]
We have some utility functions implemented in in-toto that might be a good fit for securesystemslib (see https://github.com/in-toto/in-toto/issues/80).

**Comment by lukpueh** [comment]
IMHO https://github.com/secure-systems-lab/securesystemslib/issues/35 and https://github.com/secure-systems-lab/securesystemslib/issues/75 are also related to this issue.

**Comment by lukpueh** [comment]
Fixed with #165
