### ISSUE TITLE
Add LICENSE file and tests to PyPI sdist

### ISSUE THREAD

**Issue by koobs** [secure-systems-lab/securesystemslib#166]
Downstream packagers like to use PyPI for (source) distribution files, and have those sources contain a LICENSE file and tests so we can distribute them along with any packages we ship to users, and properly QA the package locally.

At least: add `LICENSE` and graft `tests/` in `MANIFEST.in`, but preferably also add all requirements files and tox.ini/.travis.yml as they are good references for packagers to use, particularly as dependencies are often inconsistently/incorrectly declared in different places.

Our case: I'm updating the existing FreeBSD port for tuf, and currently creating a port for securesystemslib for it to depend on.

Thanks!

**Comment by lukpueh** [comment]
Thanks for the request, @koobs. I'll look into it!
