### ISSUE TITLE
Add missing git tag for 0.11.3 release

### ISSUE THREAD

**Issue by koobs** [secure-systems-lab/securesystemslib#167]
Using the GitHub sources to grab packages tests until they ship in the PyPI sdist (See #166), I noticed the git tag for the latest 0.11.3 release is missing.

This is a request to add that git tag for the commit hash which corresponds to the currently released 0.11.3 tarball on PyPI.

Our FreeBSD ports (by default), use the canonical version (0.11.3) as an argument to pass to GitHub's API to fetch a specific version of the sources. In the absence of a matching git tag, we need to use a commit hash, which can be unreliable (not *exactly* the specific version uploaded to PyPI) 

Thanks!

**Comment by lukpueh** [comment]
@koobs, the [0.11.3-release](https://github.com/secure-systems-lab/securesystemslib/releases/tag/sslibv0.11.3) was git-tagged as [`sslibv0.11.3`](https://github.com/secure-systems-lab/securesystemslib/tree/sslibv0.11.3), you can check the signatures on the release page over the [corresponding files on PyPI](https://pypi.org/project/securesystemslib/0.11.3/#files). Or is the tag-name an issue? 

@awwad, do you know why we switched to prefixing `sslib`?  AFICS the prevalent tag-formats are `v<semver>` or just `<semver>`

**Comment by koobs** [comment]
@lukpueh It's an issue with regard to automatic update detectors that downstreams use (incl FreeBSD) that look for either (or both) pure-version tags or name-version tags upstream to detect new versions.

The most standard convention that's easiest to predict/parse is: X.Y.X (no prefix/suffix)

**Comment by lukpueh** [comment]
Okay, noted for upcoming releases, @koobs. Is there anything you need us to do for past releases?

Out of curiosity, do you (others?) not scan for `v<semver>` release tags?  They seem to be pretty common too (see e.g. this not yet released [semver FAQ](https://github.com/semver/semver/blob/master/semver.md#is-v123-a-semantic-version)).

**Comment by koobs** [comment]
Anything consistent is fine, as we can codify that prefix into the 'distribution version'. That aside I prefer prefix/suffix-less (and I see more python package upstreams dropping 'v' lately), but I won't die on that hill :)

**Comment by koobs** [comment]
As far as past/future releases go, other than #166 it looks OK

**Comment by lukpueh** [comment]
I made a mental note to go back to vX.Y.Z in future releases.  And I also opened a ticket to make this a guideline (see https://github.com/secure-systems-lab/lab-guidelines/issues/20). Thanks again for your valuable input, @koobs! Closing here...
