### ISSUE TITLE
TempFile doesn't behave like a Python file object

### ISSUE THREAD

**Issue by joshuagl** [secure-systems-lab/securesystemslib#180]
This is replicating the content of theupdateframework/tuf#160, as the `TempFile` class is now implemented in securesystemslib, not tuf.

**Description of issue or feature request**:

`TempFile` isn't a [file object](https://docs.python.org/3/glossary.html#term-file-object) and its methods aren't consistent with similar methods on a [file object](https://docs.python.org/3/glossary.html#term-file-object).

**Current behavior**:

There are inconsistencies between file operations on a `securesystemslib.util.TempFile` and [file object](https://docs.python.org/3/glossary.html#term-file-object)s from the Python standard library, for example:

```python
>>> import securesystemslib.util
>>> tf = securesystemslib.util.TempFile()
>>> import tempfile
>>> ptf = tempfile.TemporaryFile()
>>> f = open('tmpfile', 'w+')
>>> tf.write(b'Hello, world!')
>>> ptf.write(b'Hello, world!')
13
>>> f.write('Hello, world!')
13
>>> tf.read(3)
b''
>>> ptf.read(3)
b''
>>> f.read(3)
''
>>> tf.read()
b'Hello, world!'
>>> ptf.read()
b''
>>> f.read()
''
>>> tf.tell()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'TempFile' object has no attribute 'tell'
>>> ptf.tell()
13
>>> f.tell()
13
>>> tf.seek(0)
>>> ptf.seek(0)
0
>>> f.seek(0)
0
>>> tf.seek(0)
>>> ptf.seek(0)
0
>>> f.seek(0)
0
>>> tf.read(3)
b'Hel'
>>> ptf.read(3)
b'Hel'
>>> f.read(3)
'Hel'
>>> tf.read()
b'Hello, world!'
>>> ptf.read()
b'lo, world!'
>>> f.read()
'lo, world!'
```

**Expected behavior**:

Users familiar with Python will expect `TempFile` to behave like a [file object](https://docs.python.org/3/glossary.html#term-file-object)

It would be a usability improvement for Python developers if `TempFile` behaved like a [file object](https://docs.python.org/3/glossary.html#term-file-object). It should probably implement [`io.FileIO`](https://docs.python.org/3/library/io.html#io.FileIO).

**Comment by joshuagl** [comment]
The main feature that `securesystemslib.util.TempFile` offers which is used in tuf is the `move()` method. I had thought about creating a lightweight subclass of `tempfile.TemporaryFile` and adding a `move()` method, but `tempfile.TemporaryFile` isn't actually a class...

My current solution is to add a helper: `securesystemslib.util.persist_temp_file()`, which takes a file object and a path and copies the former to the latter, duplicating the logic in `TempFile.move()`.

See joshuagl/securesystemslib@6c46c67212668feca9b80d35fea3b2fd10d65007

When it comes to removing `TempFile`, does securesystemslib have any policies on deprecation vs. removal?

Finally, do you have any pointers on testing securesystemslib changes with tuf? The tuf Tox file installs securesystemslib from PyPI, so I can't just run `tox`. Whereas if I try and run tuf's tests manually (with `coverage run aggregate_tests.py` the tuf module isn't found).

**Comment by lukpueh** [comment]
Regarding joshuagl/securesystemslib@6c46c67:
Looks impeccable. Feel free to PR and I'll review right away.

**Comment by joshuagl** [comment]
Thanks for the swift responses @lukpueh - expect a PR with these changes early next week.

**Comment by joshuagl** [comment]
> ```python
> >>> import securesystemslib.util
> >>> tf = securesystemslib.util.TempFile()
> >>> import tempfile
> >>> ptf = tempfile.TemporaryFile()
> >>> f = open('tmpfile', 'w+')
> >>> tf.write(b'Hello, world!')
> >>> ptf.write(b'Hello, world!')
> 13
> >>> f.write('Hello, world!')
> 13
> >>> tf.read(3)
> b''
> >>> ptf.read(3)
> b''
> >>> f.read(3)
> ''
> >>> tf.read()
> b'Hello, world!'
> >>> ptf.read()
> b''
> >>> f.read()
> ''

Reading the entire contents of the file_object, rather than from the last position, seems to have been an intention decision in `TempFile.read()`, see the comments in uses of TempFile in tuf/updater.py, i.e. [`_check_hashes()`](https://github.com/theupdateframework/tuf/blob/4fb4cb280e73958f3c9218af624d1ce731864ab1/tuf/client/updater.py#L1165).

This likely reinforces the decision to switch to using a standard file object. This behaviour of `TempFile` would be surprising to users of tuf, whereas a standard file object a user has to explicitly read all data from is more easily anticipated by those familiar with the Python standard library.

**Comment by SantiagoTorres** [comment]
Upon thinking about it, I think TF was built probably to easily set up a test harness back when unittest2 wasn't as feature-rich. It should definitely be thrown away now. Thanks @joshuagl for taking a stab at this!

**Comment by lukpueh** [comment]
@SantiagoTorres, could it be that you are thinking of  [`tuf/unittest_toolbox.py`](https://github.com/theupdateframework/tuf/blob/v0.11.2.dev3/tuf/unittest_toolbox.py)? That's yet another wrapper around python's `tempfile`, which IMHO should also be reviewed for its usefulness in 2019.
