### ISSUE TITLE
Remove securesystemslib.settings

### ISSUE THREAD

**Issue by joshuagl** [secure-systems-lab/securesystemslib#219]
**NOTE: this is a meta-bug/milestone.**

**Description of issue or feature request**:

The settings module is a legacy of securesystemslib originating as part of the tuf reference implementation and results in awkward cohesion between securesystemslib and its users.

The settings module is a prime example of this, there are places in securesystemslib where modifying the behaviour of a function requires changing values in `securesystemslib.settings`, which is non-intuitive. Particularly as many of the settings are only documented as comments in that file.

This meta-bug tracks the goal/milestone of removing `securesystemslib.settings` and should be linked to smaller, more tractable and more specific issues.

**Current behavior**:

Users have to modify securesystemslib internal settings, rather than being able to pass all required information as arguments to library functions.

**Expected behavior**:

Users are not required to modify internal library settings and can pass all required configuration values as arguments to the functions they are using.

**Comment by JustinCappos** [comment]
Makes sense to me.  Thanks for suggesting this!
