### ISSUE TITLE
Remove `keys.format_metadata_to_key()`'s dependency on `settings.HASH_ALGORITHMS`

### ISSUE THREAD

**Issue by joshuagl** [secure-systems-lab/securesystemslib#220]
**Description of issue or feature request**:

It should be possible to control the hash algorithms used for generating keyids in `securesystemslib.keys.format_metadata_to_key()` without having to change package level settings in `securesystemslib.settings`

Related to #219 

**Current behavior**:

The tuf reference implementation has code like the following, i.e. [repository_tool.py#L3062](https://github.com/theupdateframework/tuf/blob/679348ffcf99c8e6736e257f4c533f55f438a028/tuf/repository_tool.py#L3062)
```
hash_algorithms = securesystemslib.settings.HASH_ALGORITHMS
securesystemslib.settings.HASH_ALGORITHMS = key_metadata['keyid_hash_algorithms']
key_object, keyids = securesystemslib.keys.format_metadata_to_key(key_metadata)
securesystemslib.settings.HASH_ALGORITHMS = hash_algorithms
```

**Expected behavior**:

format_metadata_to_key can be called without having to change `securesystemslib.settings.HASH_ALGORITHMS`, something like:
```
key_object, keyids = securesystemslib.keys.format_metadata_to_key(key_metadata, hash_algorithms)
```

**Comment by MVrachev** [comment]
I will work to fix this one.
