### ISSUE TITLE
Create private key files with umask 177

### ISSUE THREAD

**Issue by lukpueh** [secure-systems-lab/securesystemslib#222]
**Description of issue or feature request**:
Transfer of https://github.com/theupdateframework/tuf/issues/279.

According to common practice (see e.g. ssh utilities) private key files should be created with read and write permissions for the user only (umask 177). Securesystemslib's `interface.generate_and_write_{rsa, ed25519, ecdsa}_keypair` functions should adopt that behavior.

**Current behavior**:
Private key files are created with the OS' default umask.

**Expected behavior**:
Private keys files are created with umask 177.

**Comment by lukpueh** [comment]
I suggest to update `securesystemslib.util.persist_temp_file` to take an optional octal permissions argument and pass `600` in `interface.generate_and_write_{rsa, ed25519, ecdsa}_keypair` functions.

**Comment by sechkova** [comment]
Looking at the issue, I noticed that the intention is 

> private key files should be created with read and write permissions for the user only

which means _file permissions_ 600 and _umask_ 177 (umask unsets the bits).
Can you confirm that my understanding is correct here?

**Comment by lukpueh** [comment]
You are absolutely right, @sechkova! Thanks for pointing this out. :)

**Comment by joshuagl** [comment]
Fixed in #231
