### ISSUE TITLE
Better distinguish between keytype and scheme for ECDSA keys

### ISSUE THREAD

**Issue by adityasaky** [secure-systems-lab/securesystemslib#239]
**Description of issue or feature request**:

The key format provided by `securesystemslib` defines a `keytype` field and a `scheme` field. Currently, there is no distinction between these fields for ECDSA keys.

**Current behavior**:

ECDSA keys have the following format:

```
{
    "keytype" : "ecdsa-sha2-nistp256",
    "scheme" : "ecdsa-sha2-nistp256",
    "keyval" : {"public" : PUBLIC}
}
```
As noted in https://github.com/secure-systems-lab/securesystemslib/commit/761aded9968cb380004a86c44eb4796c061bca9c, `ecdsa-sha2-nistp384` is also supported by `securesystemslib`.

**Expected behavior**:

Update `securesystemslib` to use just `ecdsa` as `keytype` while retaining the current scheme formats. This also aligns with the key format for RSA keys where we have:

```
{
    "keytype" : "rsa",
    "scheme" : "rsassa-pss-sha256",
    "keyval" : {"public" : PUBLIC}
}
```

**Comment by shibumi** [comment]
Good work, I just want to mention, that in in-toto-golang we currently follow the expected behavior:

```
{
    "keytype" : "ecdsa",
    "scheme" : "ecdsa-sha2-nistp256",
    "keyval" : {"public" : PUBLIC}
}
```

**Comment by lukpueh** [comment]
Closed by https://github.com/secure-systems-lab/securesystemslib/pull/267
