### ISSUE TITLE
Configure automatic code linter

### ISSUE THREAD

**Issue by lukpueh** [secure-systems-lab/securesystemslib#243]
**Description of issue or feature request**:
- Configure linter (e.g. pylint) to analyze all securesystemslib code including tests
- Configure tox+travis to run linter on PR and require full pass
- Fix linter errors/warnings in all securesystemslib code including tests

See https://github.com/in-toto/in-toto/issues/289, https://github.com/in-toto/in-toto/pull/296, https://github.com/in-toto/in-toto/pull/279 for an exemplary setup, also see how commits are aggregated by error/warning type, to mitigate the flag day.

**Current behavior**:
No automatic code linting and unlinted code

**Expected behavior**:
Automatic code linting and linted code

**Comment by trishankatdatadog** [comment]
I propose trying GitHub's LGTM static analysis tool: https://lgtm.com/projects/g/theupdateframework/tuf/?mode=list

**Comment by lukpueh** [comment]
*python-tuf* uses *black*, *isort* and *pylint* these days and I'm very happy with the setup because it has eliminated code style discussions (see [invocation](https://github.com/theupdateframework/python-tuf/blob/6e20c314467631f28c36a3d6ee06f08b48725b6e/tox.ini#L44-L46) and [config](https://github.com/theupdateframework/python-tuf/blob/6e20c314467631f28c36a3d6ee06f08b48725b6e/pyproject.toml#L77-L135)).

Let's do the same thing at least for any newly added modules in *securesystemslib*.

**Comment by joshuagl** [comment]
💯
