### ISSUE TITLE
Split up util.get_file_details()

### ISSUE THREAD

**Issue by joshuagl** [secure-systems-lab/securesystemslib#246]
**Description of issue or feature request**:

`util.get_file_details()` returns the length and hashes of the specified file. This makes a lot of sense for generating information about TUF targets, where the length and hashes of each target are required, but is potentially too costly a function when generating information about TUF metadata files for the snapshot role, where lengths and hashes are optional. Snapshot metadata may only want hashes, or only want lengths, and we don't want to force an adopter to implement their own subset of the functionality in `get_file_details()`.

Therefore I suggest we factor out the two features of `get_file_details()` into two new utility functions – one for length and one for hashes – and have the existing `get_file_details()` wrap them.

**Current behavior**:

Callers wanting to compute length or hashes, not both, need to either accept the overhead of unwanted computations in `get_file_details()` (only a significant problem for hashes), or implement their own equivalent functionality.

**Expected behavior**:

A separate API is provided for at least hash computation, ideally hash and length computation, with `get_file_details()` conveniently wrapping both.
`get_file_details(filepath, hash_algorithms=['sha256'], storage_backend=None)`
`get_file_length(file_path, storage_backend=None)`
`get_file_hashes(file_path, hash_algorithms=['sha256'], storage_backend=None)`

**Comment by joshuagl** [comment]
@lukpueh are you aware of `get_file_details()` being used outside of the tuf reference implementation? I don't see it used in a quick `git grep` of in-toto.

Maybe this would be better as two utility functions in securesystemslib and a convenience wrapper in tuf?

**Comment by lukpueh** [comment]
I know that it is not used in in-toto. We [hash files directly with `securesystemslib.hash`](https://github.com/in-toto/in-toto/blob/6f7f5cc8d2955c511f6774df178ed376798815bc/in_toto/runlib.py#L68). A quick grep through sslib's  [dependents](https://github.com/secure-systems-lab/securesystemslib/network/dependents) does not reveal any usage either. I'm fine with moving the wrapper to tuf. :)

**Comment by joshuagl** [comment]
Resolved in #259
