### ISSUE TITLE
Don't use CLI gpg

### ISSUE THREAD

**Issue by KOLANICH** [secure-systems-lab/securesystemslib#247]
Usage of CLI tools may be dangerous. It is also not a very clean and powerful approach because CLIs are quite limited.

The better approach is to use some libs directly.

gpgme (debian package `python3-gpg` and is imported as `gpg`) is claimed to be LGPL, but it is a bit strange, since gpg itself is GPL.

There is also https://github.com/SecurityInnovation/PGPy , a pure python impl that is pretty abandoned.

Also BouncyCastle can be used via JPype.

**Comment by joshuagl** [comment]
Note that gpgpme *is* a wrapper of the gpg CLI tool, with often [surprising behaviour](https://github.com/justinsteven/advisories/blob/master/2020_fwupd_dangling_s3_bucket_and_CVE-2020-10759_signature_verification_bypass.md#gpgme-gnupg-made-easy). Furthermore, because it's a C library which would need to be installed with the Python bindings it makes our installation story, particularly on non-Linux systems, much more difficult.

**Comment by lukpueh** [comment]
Thanks for submitting this issue, @KOLANICH. We did review alternatives back when we implemented this. Unfortunately, *gpgme* did not work out of the box and, as @joshuagl points out, would have added more native dependencies.

Our use case here is to provide a bridge between securesystemslib infrastructure (data containers, verifications routines) and gpg keys, to developers that already have and use gpg e.g. for mail, git, software signing, etc. ...
Wrapping the cli seemed the most feasible approach and suited our needs. That said, we welcome any feedback, especially if it is related to the security of our project.

**Comment by lukpueh** [comment]
cc @SantiagoTorres

**Comment by KOLANICH** [comment]
>Note that gpgpme is a wrapper of the gpg CLI tool

I doubt it very much. Its source code doesn't look like that. Could you prove it?

>Wrapping the cli seemed the most feasible approach and suited our needs.

There was already a wrapper for cli. A pure python one. Called python-gnupg. With vulnrs. Please never use CLI for passing any args.

**Comment by SantiagoTorres** [comment]
> I doubt it very much. Its source code doesn't look like that. Could you prove it?

Sure [here](https://git.gnupg.org/cgi-bin/gitweb.cgi?p=gpgme.git;a=blob;f=src/engine-gpg.c;h=173e940c205bc81dc0f0e931241d0bc7719c17e2;hb=HEAD#l1643)

**Comment by SantiagoTorres** [comment]
I do want to make sure you understand that we are calling gpg for signing exclusively, for verification we implement our own RFC4880 signature parsing and verification.

**Comment by KOLANICH** [comment]
>Sure here

Thanks for the info, it really does this. I feel like I should have to stop using gpgme. 

>I do want to make sure you understand that we are calling gpg for signing exclusively, for verification we implement our own RFC4880 signature parsing and verification.

Thanks, but signing is also important. BTW, I wonder if it is possible to create python bindings to sequoia-pgp?

**Comment by lukpueh** [comment]
It looks like this questions has been answered. Closing..
