### ISSUE TITLE
Revise module architecture and define clear API modules and functions

### ISSUE THREAD

**Issue by lukpueh** [secure-systems-lab/securesystemslib#270]
**Description of issue or feature request**:
Securesystemslib lacks of a clear public API. It should be clear and intuitive for users of secureystemslib, which modules and which functions are public API.

**Current behavior**:
API is scattered across:

- for *general* key operations (generate, import, sign, verify)
  - `keys.py` -- high-level public interface to sign/very (key type independent), and generate and import keys (key type dependent). Calls into low-level non-public `{rsa, ecdsa, ed25519}_keys.py` modules, which are (mostly) separated by key type.
  - `interface.py` -- higher-level public interface (mostly calls into `key.py`) to generate and import keys

- for GPG key operations (import, sign, verify)
  - `gpg/functions.py` -- public interface for gpg subpackage, independent from above key operations.

- for other other non-key related operations
  - `hash.py` -- facade for `hashlib` from stdlib and `cryptography.hazmat.primitives.hashes`
  - `process.py` -- thin subprocess wrapper
  - `storage.py`-- file system abstraction 
  - `util.py` -- mostly I/O related utils
  - `formats.py`-- schema definition constants (likely to be deprecated, see https://github.com/secure-systems-lab/securesystemslib/issues/183), OLPC canonical json implementation 

 
**Expected behavior**:
Revise module architecture to use mnemonic names for (public) modules (not `interface` or `functions`) appropriate for the interface functions they contain. Also see discussion about [import guidelines](https://github.com/secure-systems-lab/code-style-guidelines/issues/20#issuecomment-679225442).

**Comment by trishankatdatadog** [comment]
💯 💯 💯

**Comment by MVrachev** [comment]
Overall the suggestions sound good. 

On the topic of `RSASigner` example (as @lukpueh has already heard my opinion :D) I am not a fan of adding an inheritance just for the sake of simpler implementation without logical connection.
In this example, I don't see a logical relationship between `RSASigner` and `RSAPrivateKey`.
This of course is just my opinion and the maintainers should decide. 

One minor naming suggestion - why don't we use `SSlibSigner` instead of `SslibSigner`?
That's for all naming suggestions, I think double upper case `S` looks better.

**Comment by lukpueh** [comment]
> One minor naming suggestion - why don't we use SSlibSigner instead of SslibSigner?
That's for all naming suggestions, I think double upper case S looks better.

Agreed, the class in securesystemslib is actually called `SSlibSigner`.  I'll update comments above...

**Comment by lukpueh** [comment]
> In this example, I don't see a logical relationship between RSASigner and RSAPrivateKey.

The connection is that there is a 1-to-1 relationship between signing and private key (for tuf/in-toto), so it is possible to combine them in one class.

Of course, you could create an `RSASigner` class, which has an `RSAPrivateKey` attribute, but for our use case I don't see the benefit over having just one class that contains both the private key data and also has a sign method. You could call this one class either `RSASigner` or `RSAPrivateKey`, but for tuf/in-toto we care more about the signing aspect and less about the key aspect. Also, sometimes the signer isn't even a key, but just a reference to a key (e.g. GPGSigner - #341).

**Comment by jku** [comment]
my improvement ideas are in https://docs.google.com/document/d/1KQY5v1ASXpZM5GhfATV_WJf7GaMJrfBOXr06dtxc-ps/ but I'll summarize here -- just adding to what Lukas already listed. I believe this leads us to an API that is complete: users only need Key + Signer, there is no need to import any other securesystemslib modules.

Signer
* Signer can have multiple implementations (e.g. GCPKMSSigner, PGPSigner, SigstoreSigner), in SSLib or outside
* users of Signer API should not need to use the specific implementation, just Signer API. This covers Signer construction and signing
* signers are constructed using a "private key URI" configuration value that encodes both Signer implementation and the private key content location (see doc for details)
* the one special case where users would need the specific implementation is new key generation/import: these would be implementation specific methods
* Signer always has access to the corresponding Key (this makes many things easier)

Key
* Key can have multiple implementations, in SSLib or external
* users of Key API should never need to use the specific implementation, only the generic Key API. This includes serialization, deserialization and signature verification

**Comment by jku** [comment]
I tend to agree that smaller specific implementations (e.g. RSAKey) would be good but note that if we manage what is proposed above, it is only relevant to users for the specific case of key generation/import. Otherwise how the implementation is split is an implementation detail that we can change without breaking API.

**Comment by lukpueh** [comment]
#731 has removed much of the legacy "API" in favour of `securesystemslib.signer`. IMO this new Signer API is relatively clear and well documented. Remaining documentation deficits are described in reasonably scoped issues (see "docs" label).

Apart from `securesystemslib.signer` we still have a few modules/subpackages, which don't fit in quite well, but also can't just be removed. 

- `hash.py`, `storage.py` and `secureysystemslib.gpg` -- I'd like to treat them as public but hidden API, to be used by in-toto and/or tuf. No idea how to best express this. Maybe make them public but document that they are for "internal" use?

- `dsse.py` and `formats.py` -- I think it's okay to treat them as public API, because they are reference implementations related to the two signature wrapper paradigms established by tuf and in-toto.
