### ISSUE TITLE
Add metadata container classes for signed metadata

### ISSUE THREAD

**Issue by lukpueh** [secure-systems-lab/securesystemslib#272]
**Description of issue or feature request**:
Both [TUF](https://github.com/theupdateframework/tuf/pull/1112) and [in-toto](https://github.com/in-toto/in-toto/blob/55acb5d376dca9aebba1ffb5e7e5357283b40ff6/in_toto/models/common.py) use a class based model for their metadata, with a similar signature wrapper class. The signature container (i.e. `Metadata`) and the base class for the `signed` contents (i.e. `Signed`) could be hosted in `securesystemslib` to re-use code and to better draw the line between in-toto/tuf concepts and pure cryptographic signing.

**Current behavior**:
No class-based metadata model.

**Expected behavior**:
Add class-based metadata model. 

*NOTE: I strongly suggest to adopt the classes that where recently added to TUF (theupdateframework/tuf#1112), which were based on the the ones from in-toto but don't use the 3rd-party `attrs` package and slightly streamline the design (most notably see recursive serialisation functions `from_dict`and `to_dict`).*

**Caveat**:

A  [`from_dict` factory method on a generic `Metadata` class](https://github.com/theupdateframework/tuf/pull/1112/files#diff-d2aa622cc58ad47011c52d0adc99323dR143-R184) needs to know about the specific contained metadata, i.e. the subclass of `Signed` (e.g. `tuf.Targets`, `tuf.Snapshot`, `in_toto.Link, in_toto.Layout`, etc..), which will not be implemented in securesystemslib.

Possible solutions: 
- Provide a way to register a `signed._type`-to-subclass-of-`Signed` mapping on the  `Metadata` class
- Sub-class `Metadata` in tuf and in-toto and implement the factory there, e.g. `class tuf.Metadata(securesystemslib.Metadata)`

**Comment by lukpueh** [comment]
In regards to the implementation of de/serialization from and to different wireline formats, as well as canonicalization, what do others prefer? Implement these as different (1) methods on a generic class or use (2) subclassing? E.g.:

(1)`Metadata.to_json(self)`,  `Metadata.to_asn1(self)`, `Signed.to_canonical_json_bytes(self)`, etc...
or
(2) `JSONMetadata(Metadata)`, `ASN1Metadata(Metadata)`, `OLPCCanonicalJsonSigned(Signed)`, etc...

I have a slight preference for (1) which is why I implemented it that way in [tuf#1112](https://github.com/theupdateframework/tuf/pull/1112). It seems a bit less *engineered* and also more explicit in it's usage.  (2) OTOH might be more flexible and also feels purer in an OOP-sense.

Thoughts?

**Comment by joshuagl** [comment]
I have a slight preference for (2), but only because I think it makes it easier for adopters to implement the wireline format they care about in their own project and plug it in to securesystemslib and therefore tuf/in-toto. I'm imagining an interface, much like the `StorageBackendInterface`

**Comment by joshuagl** [comment]
I suspect in-toto's interest may depend on the progress of [ITE-6](https://github.com/in-toto/ITE/pull/15) and how long they intend to retain support for the pre ITE-6 link format. Would certainly be good to hear from in-toto maintainers.

**Comment by adityasaky** [comment]
If I'm not mistaken, the Metablock / Metadata parts are more ITE-5 than ITE-6. I think I'm in favour of using sslib for that, because any upcoming Python support for signing-spec could also naturally be a part of sslib then.

I think the signed / signable formats are very project specific though? So worth keeping them in the respective implementations?

**Comment by SantiagoTorres** [comment]
I think it'd be wortwhile to maybe move this class to sslib... This would in fact reflect the intention of ITE-5, which is to dissociate the signature wrapper from the spec, and allow for implementers to use their own (while at the same time blessing the sslib block as a recommended, default format)

**Comment by lukpueh** [comment]
DSSE is in securesystemslib and might replace traditional Metadata at some point. It's not worth to move the two working Metadata implementations from tuf and in-toto Python implementations to securesystemslib.
