### ISSUE TITLE
import-style prevents vendoring

### ISSUE THREAD

**Issue by jku** [secure-systems-lab/securesystemslib#281]
The import style used in securesystemslib:
`import securesystemslib.module`
is incompatible with vendoring (because it would like to modify the import to `from my.vendored.path import  securesystemslib.module` but that is invalid syntax)

Executable failure example:
https://gist.github.com/jku/22d5f08083c8b7b2f3e552f7ca6c301e

This is mostly a "heads-up": I'm exploring solutions in the TUF issue https://github.com/theupdateframework/tuf/issues/1165 and will likely suggest whatever solution is found here.

**Comment by joshuagl** [comment]
See https://github.com/secure-systems-lab/securesystemslib/pull/254 which proposed one possible solution for this

**Comment by jku** [comment]
So the option that does not need a massive code change (and lets securesystemslib use the namespacing it now does) is to have a module that imports all the other modules (if this module is __init__.py it works nicely but I don't think that's a requirement). 

Now the other modules can import the common module instead of the individual modules (and we hope python does not go into an eternal import-loop) and old code should function just like before because the namespace "securesystemslib.<module>" is still defined. I have no idea if this is a crime against package design or not

**Comment by jku** [comment]
Fixed in #316 !
