### ISSUE TITLE
blake2b digest length is incompatible with Warehouse

### ISSUE THREAD

**Issue by jku** [secure-systems-lab/securesystemslib#282]
**I believe the blake2b hashes produced by warehouse and securesystemslib  are incompatible**

I can't actually run the full update cycle with my pip-branch against the Warehouse tuf-branch yet but I've taken another look at the metadata and I'm fairly sure we will be incompatible in the hash verification step.

This is what Warehouse target metadata currently looks like: 
```
"0b/de/ae38ae748ae74093a0c8abad03d83e179870639d2d1b092ba4b3e82164df/litefeel_pycommon-0.1.1-py3-none-any.whl": {
    "custom": {
     "backsigned": true
    },
    "hashes": {
     "blake2b": "0bdeae38ae748ae74093a0c8abad03d83e179870639d2d1b092ba4b3e82164df"
    },
    "length": 3077
   }
```

A TUF client compares that "blake2b" hash to one that securesystemslib produces for the given data, something like this simplified example:
```
>>> dobj = securesystemslib.hash.digest("blake2b")
>>> dobj.update(b'')
>>> dobj.hexdigest()
'786a02f742015903c6c6fd852552d272912f4740e15847618a86e217f71f5419d25e1031afee585313896444934eb04b903a685b1448b755d56f701afe9be2ce'
```

The digests have different lengths. Warehouse uses blake2b-256 and TUF uses blake2b-512 (which is the maximum).

So:
* First, is the warehouse choice set in stone? I can see how it kind of might be as the shorter hash is already used in many places (ping @woodruffw)
* If it is, we probably want to support at least a new "blake2b-256" hash name (and add the little bit of new code needed in `hash.py::digest()`)

I can do the PR if there's consensus.

**Comment by lukpueh** [comment]
Thanks for catching this. I'm fine either way. In case you haven't looked it up yet, in hashlib we get `"blake2b-256"` with `hashlib.blake2b(digest_size=32)` or  `hashlib.new("blake2b", digest_size=32)`.`pyca/cryptography`'s hash interface doesn't seem to support blake2b-256.

**Comment by woodruffw** [comment]
To answer my part: yes, the current Warehouse usage is (more or less) set in stone: it's part of the DB schema and is already present in a number of other artifacts of the Warehouse packaging pipeline.
