### ISSUE TITLE
GPG tests fail on windows

### ISSUE THREAD

**Issue by jku** [secure-systems-lab/securesystemslib#339]
If windows is enabled in CI workflow, the GPG signing tests fail with timeout:

```
TimeoutExpired: Command '['gpg', '--detach-sign', '--digest-algo', 'SHA256', '--homedir', 'c:/users/runner~1/appdata/local/temp/tmprxgwki/rsa']' timed out after 3 seconds
```

Removing the timeout gives a bit of relevant output:
```
gpg: starting migration from earlier GnuPG versions
gpg: can't connect to the agent: IPC connect call failed
gpg: error: GnuPG agent unusable. Please check that a GnuPG agent can be started.
gpg: migration aborted
gpg: can't connect to the agent: IPC connect call failed
gpg: can't connect to the agent: IPC connect call failed
gpg: keydb_search failed: No agent running
gpg: no default secret key: No agent running
gpg: signing failed: No agent running 
```
I tried to reproduce outside of securesystemslib but could not: This worked just fine on github (without any extra output):
`gpg --detach-sign --digest-algo SHA256 --local-user 8465A1E2E0FB2B40ADB2478E18FB3F537E0C8A17 --homedir rsa`
:shrug: 

This blocks #326

**Comment by jku** [comment]
failure output with `timeout=None` https://github.com/jku/securesystemslib/runs/1960882376

**Comment by lukpueh** [comment]
in-toto tests that use `securesystemslib.gpg` do seem to work, see e.g. https://github.com/SolidifiedRay/in-toto/runs/1949133032?check_suite_focus=true#step:7:131

**Comment by lukpueh** [comment]
It fails because it cannot handle the absolute `homedir` paths passed from the tests (see #517). I'll submit a quick fix (pass relative paths in tests), along with other #507-blockers shortly.

**Comment by lukpueh** [comment]
Closed by https://github.com/secure-systems-lab/securesystemslib/pull/518
