### ISSUE TITLE
Add type annotations

### ISSUE THREAD

**Issue by jku** [secure-systems-lab/securesystemslib#358]
We should type annotate our functions:
* Most importantly we should type annotate public methods (this should enable TUF to type check its calls)
* internal methods are useful to annotate as well (and may be necessary to enable static type checking in this repo)

This is companion to #357 (using mypy in securesystemslib): I think the process goes like this (although it's partially speculation: I've not tried this yet)
* annotate at least one module (at least the public methods)
* when public methods are annotated, this module can be enabled in TUF mypy config
* when one whole module is annotated, we can do #357 and start type checking here

Repeat steps for each module

[Using mypy with an existing codebase](https://mypy.readthedocs.io/en/stable/existing_code.html) may be useful: we may want to try tools to automatically generate type annotations: they might work well for this sort of code

**Comment by sechkova** [comment]
`mypy` is now included in the CI run with #361.
 Also the `util` and `storage` modules are type annotated with #361 and #362.

**Comment by jku** [comment]
The other modules used in TUF (metadata api) are:
```
exceptions
formats
keys
signer
```
So I guess those should be next in line (but I think we could also enable checks in TUF module-by-module if there are trickier modules that can't be annotated in the next weeks)

**Comment by jku** [comment]
Also, I think we need to add a `securesystemslib/py.typed` marker file in the repo: https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-type-hints-for-third-party-library
Otherwise TUF can't use the SSLib annotations (and we definitely want that because we want to find things like https://github.com/theupdateframework/tuf/pull/1442)

**Comment by jku** [comment]
> Also, I think we need to add a securesystemslib/py.typed

3 years later this is still true :joy:
