### ISSUE TITLE
accept Signature in verify_signature()

### ISSUE THREAD

**Issue by jku** [secure-systems-lab/securesystemslib#360]
A signature object was added into SSLib but verify_signature() wasn't updated to accept it. 
It leads to weird code:

```python
if not sslib_keys.verify_signature(
    sslib_key,
    signature.to_dict(), # <- why am I serializing the signature here ?
    data,
):
    print ("oh no")
```

**Comment by lukpueh** [comment]
I think we can change this into a "refactor internals of new signer API"-issue. cc @jku

**Comment by jku** [comment]
Yes I think I'm fine with closing this... If the signer module provides me with everything I as a user need, I don't really care how the keys module operates.
