### ISSUE TITLE
formats: consider add INTEGER_SCHEMA and FLOAT_SCHEMA

### ISSUE THREAD

**Issue by Dentrax** [secure-systems-lab/securesystemslib#367]
**Description of issue or feature request**:

It would be great if we have the `INTEGER_SCHEMA` and `FLOAT_SCHEMA` formats. We can use these schemas in order the validate whether the given content is in _integer_ or _float_ format.

Actually, there is already an [Integer class](https://github.com/secure-systems-lab/securesystemslib/blob/9905f67bbca4344168b708aea0833256d4dfe803/securesystemslib/schema.py#L583) in the schema file, we can easily use this:

```python
def check_match(self, object):
    if isinstance(object, bool) or not isinstance(object, int):
      # We need to check for bool as a special case, since bool
      # is for historical reasons a subtype of int.
      raise exceptions.FormatError(
          'Got ' + repr(object) + ' instead of an integer.')
```

At the end of the day, this is what will we have:
```python
ANY_INTEGER_SCHEMA = SCHEMA.AnyInteger()
ANY_FLOAT_SCHEMA = SCHEMA.AnyFloat()
```

**Comment by lukpueh** [comment]
obsolete via #776
