### ISSUE TITLE
Debian Package Auto-Building fails for python-securesystemslib (0.23.0-1) on all (can't reproduce)

### ISSUE THREAD

**Issue by lukpueh** [secure-systems-lab/securesystemslib#407]
**Full Log** 

https://buildd.debian.org/status/fetch.php?pkg=python-securesystemslib&arch=all&ver=0.23.0-1&stamp=1650975203&raw=0

**Trace**
```python
======================================================================
FAIL: test_rsa (test_interface.TestInterfaceFunctions)
Test RSA key _generation and import interface functions.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.10_securesystemslib/build/tests/test_interface.py", line 249, in test_rsa
y    self.assertTrue(err_msg in str(ctx.exception),
AssertionError: False is not true : expected: 'Bad decrypt. Incorrect password?' got: 'RSA (public, private) tuple cannot be generated from the encrypted PEM string: Could not deserialize key data. The data may be in an incorrect format or it may be encrypted with an unsupported algorithm.' (row 4)
```

**Context**

We test the import of an ad-hoc created encrypted private RSA key supplying the wrong password, and expect a specific error message from the underlying `cryptography` library (i.e. "Bad decrypt. ..."), but get something else (i.e. "Could not deserialize key data ...").
https://github.com/secure-systems-lab/securesystemslib/blob/47a6fdfa728ab8cdc3bdb71f70b16a7d404b4f58/tests/test_interface.py#L239-L251

The original error is raised in [cryptography v3.4.8-1.../backend.py#L1463-1494](https://salsa.debian.org/python-team/packages/python-cryptography/-/blob/debian/3.4.8-1/src/cryptography/hazmat/backends/openssl/backend.py#L1463-1494). Note that the received error message could have been raised in two places of the if/else-switch.

**Investigation**
- The failure can't be reproduced using the same version of  `cryptography` as the failing build. And even for the failing build the tests run on Python 3.9 and 3.10 with the same version of `cryptography` but only fail on 3.10.

- Maybe the backend used by `cryptography` (LibreSSL, OpenSSL, custom rust implementation?), which set the condition to raise either of expected or actual errors, differs between the failing build and the attempted reproducers?

- Also the tested [ad-hoc created RSA key](https://github.com/secure-systems-lab/securesystemslib/blob/47a6fdfa728ab8cdc3bdb71f70b16a7d404b4f58/tests/test_interface.py#L162) file does not seem to be corrupted, because it can be [imported successfully earlier in the same test](https://github.com/secure-systems-lab/securesystemslib/blob/47a6fdfa728ab8cdc3bdb71f70b16a7d404b4f58/tests/test_interface.py#L167-L173) when supplying the correct password.

**Comment by jku** [comment]
It does look like openssl returns something different so cryptography then raises with a different message. This of course should not depend on python version in any way so that doesn't make this any clearer...

**Comment by lukpueh** [comment]
Here's a minimal reproducer using the relevant `cryptography` functions only. Now we just have to find the environment, where this fails:

```python
from cryptography.hazmat.backends.openssl.backend import backend
from cryptography.hazmat.primitives.asymmetric.rsa import generate_private_key
from cryptography.hazmat.primitives.serialization import (
    BestAvailableEncryption,
    Encoding,
    PrivateFormat,
    load_pem_private_key,
)

PW = b"password"
BAD_PW = b"bad pw"

# Create encrypted private key, as 'securesystemslib' would do it
private_key = generate_private_key(
    public_exponent=65537, key_size=3072, backend=backend
)
private_pem = private_key.private_bytes(
    encoding=Encoding.PEM,
    format=PrivateFormat.TraditionalOpenSSL,
    encryption_algorithm=BestAvailableEncryption(PW),
)

# Should load successfully
load_pem_private_key(private_pem, PW, backend=backend)

# Should fail with "Bad decrypt." (raise if it doesn't)
try:
    load_pem_private_key(private_pem, BAD_PW, backend=backend)
except ValueError as e:
    if not "Bad decrypt." in str(e):
        raise
else:
    raise
```

**Comment by lukpueh** [comment]
The issue did not re-occur on a re-build and *[python-securesystemslib 0.23.0-1 has migrated to testing](https://tracker.debian.org/news/1324723/python-securesystemslib-0230-1-migrated-to-testing/)*. I'm inclined to attribute the failure to a hiccup on the build system (for whatever that means). At least it does not seem like something we can fix in our code. Closing here...
