### ISSUE TITLE
Ability to create ED25519KEY_SCHEMA key from ed25519 private key value

### ISSUE THREAD

**Issue by dennisvang** [secure-systems-lab/securesystemslib#408]
**Description of issue or feature request**:

Suppose I have an ed25519 private key value as bytes (not encrypted). Basically, this private key value represents the seed for the `nacl.signing.SigningKey`.

Feature request: 

I would like to be able to import this private key value, in order to get a dict that conforms to [securesystemslib.formats.ED25519KEY_SCHEMA][1].

Use case:

User needs to sign some data using `securesystemslib`, but only has the raw private key value available, instead of a key file. The private key value could come from an environment variable or from the command line, for example.

**Current behavior**:

It is not obvious to me if this is currently possible.

- The idea is similar to [securesystemslib.keys.import_ed25519key_from_private_json][2], except that we now only have a private key value as input.

- The implementation of [securesystemslib.keys.generate_ed25519_key][3] comes close, if only it would have an optional `private_key` argument, from which the public key could then be calculated using the `nacl.signing.SigningKey`.

- There is [securesystemslib.keys.format_keyval_to_metadata][5], but that does not seem to cover the complete ED25519KEY_SCHEMA.

**Expected behavior**:

If such a feature were considered desirable, here are some options:

- create a separate function, e.g. `def import_ed25519key_from_private_key_value(private_key_value: bytes)`, or
- adapt [securesystemslib.ed25519_keys.generate_public_and_private][4] and [securesystemslib.keys.generate_ed25519_key][3], as follows:

    ```python
    def generate_public_and_private(seed: Optional[bytes] = None):
        ...
        if seed is None:
            seed = os.urandom(32)
        ...
    ```
    and then 
    ```python
    def generate_ed25519_key(scheme='ed25519', private_key: Optional[bytes] = None):
        ...
        public, private = ed25519_keys.generate_public_and_private(seed=private_key)
        ...
    ```
- ...

[1]: https://github.com/secure-systems-lab/securesystemslib/blob/015233d9742ace3546e2a30d1c13d922d5908af4/securesystemslib/formats.py#L274
[2]: https://github.com/secure-systems-lab/securesystemslib/blob/015233d9742ace3546e2a30d1c13d922d5908af4/securesystemslib/keys.py#L1572
[3]: https://github.com/secure-systems-lab/securesystemslib/blob/015233d9742ace3546e2a30d1c13d922d5908af4/securesystemslib/keys.py#L286
[4]: https://github.com/secure-systems-lab/securesystemslib/blob/015233d9742ace3546e2a30d1c13d922d5908af4/securesystemslib/ed25519_keys.py#L90
[5]: https://github.com/secure-systems-lab/securesystemslib/blob/015233d9742ace3546e2a30d1c13d922d5908af4/securesystemslib/keys.py#L364

**Comment by jku** [comment]
I think this is now possible with `SSlibKey.from_crypto()`: https://github.com/secure-systems-lab/securesystemslib/blob/main/docs/CRYPTO_SIGNER.md: If cryptography can read it, it should work.
