### ISSUE TITLE
Always using pycrypto for key generation

### ISSUE THREAD

**Issue by awwad** [secure-systems-lab/securesystemslib#43]
In [the current keys.py, line 1702](https://github.com/secure-systems-lab/securesystemslib/blob/e35fc017f8676b9f6402e23c7ea0320872dd7687/securesystemslib/keys.py#L1702), regardless of which library you are configured to use (pycrypto or pyca_crypto), pycrypto is used to generate key files. This appears to be a typo / minor oversight, since there is logic to choose one or the other.

This is related to issue #44, in that it also complicates inconsistent passphrase treatment.

In any case, this prevents you from generating keys if you don't have pycrypto installed. (That should be supported: you're allowed to use pyca_crypto and not pycrypto if you want.)

It is also worth considering configuring `tox.ini` to do an integration test for this: run once with only pycrypto (not pyca_crypto) installed, once with only pyca_crypto (not pycrypto) installed, etc.

**Comment by vladimir-v-diaz** [comment]
Fixed in https://github.com/secure-systems-lab/securesystemslib/commit/e8aafd8afbf7b8cae9d4eac2f01275dfbbfa27f0.
