### ISSUE TITLE
Inconsistent passphrase treatment on key generation / loading

### ISSUE THREAD

**Issue by awwad** [secure-systems-lab/securesystemslib#44]
## Bug
First, if you use `repository_tool` and try generating an rsa key (`rt.generate_and_write_rsa_keypair`) and don't provide a passphrase (by just hitting enter at the prompts), `repository_tool` generates an unencrypted PEM file (always using pycrypto -- see #43).

It makes some sense to support unencrypted key files, so this is fine. Two problems result from the code, though, aside from those mentioned in #43:
- There is no way provided to instruct `repository_tool` to tell **pyca_crypto** to try to load an unencrypted PEM file, so the keys you just generated (with **pycrypto**) become unusable.
- There is no way provided to instruct `repository_tool` to tell **pyca_crypto** to generate an unencrypted PEM file.

## Analysis and Steps
Three options are desired for key generation using `repository_tool.generate_and_write_rsa_keypair` and `repository_tool.import_rsa_privatekey_from_file` and their intersection is complicating things:
- no passphrase; don't encrypt the PEM file  /  load an unencrypted PEM file
- here's a passphrase to use; encrypt the created PEM file or load the encrypted PEM file
- prompt me for a passphrase; encrypt the created PEM file or load the encrypted PEM file

It must be possible to do each (assuming we support unencrypted PEM files) and clear to the user how to do each. Further, it must be consistent behaviorally across calls to pyca_crypto and pycrypto.

**Comment by vladimir-v-diaz** [comment]
This issue was fixed in pull request https://github.com/secure-systems-lab/securesystemslib/pull/46.
