### ISSUE TITLE
RFE: private key reference scheme

### ISSUE THREAD

**Issue by jku** [secure-systems-lab/securesystemslib#447]
Taking this out of #445 as I think it makes sense in general, not just in KMS:

### Idea

Let's define an identification scheme for private key materials in Signer: 
* allows applications that sign (TUF repository, or a CLI signing tool)  to reference a specific private key, regardless of private key "storage" method
* allows changing key "storage" (e.g. from RSA-key-in-file to GPG key) with configuration, no code changes needed
* simple so that it works on CLI and configuration files
* covers all private key types: private key files, GPG, yubikeys, KMS...

### sigstore ReferenceScheme

sigstore has a `ReferenceScheme` for their KMS abstraction: I think that would work for private keys in general
https://github.com/sigstore/sigstore/tree/main/pkg/signature/kms. There's no requirement to be 1:1 compatible with sigstore, just showing this as a reference of something we could copy.

### Proposal

https://docs.google.com/document/d/1KQY5v1ASXpZM5GhfATV_WJf7GaMJrfBOXr06dtxc-ps

Review welcome here or in the doc!

**Comment by jku** [comment]
Almost complete proposal https://docs.google.com/document/d/1KQY5v1ASXpZM5GhfATV_WJf7GaMJrfBOXr06dtxc-ps -- still debating myself if I should propose a Key class as well: this is definitely ready for review

**Comment by lukpueh** [comment]
> still debating myself if I should propose a Key class as well 

FYI: There's new `Key`-related work available downstream in [in-toto/securesystemslib](https://github.com/in-toto/securesystemslib/blob/master/securesystemslib/key.py). This is part of https://github.com/secure-systems-lab/securesystemslib/issues/370

**Comment by joshuagl** [comment]
@kairoaraujo would love your input on the design here, especially:
* URI scheme key reference
* Importing existing keys (i.e. SSH key or YubiKey) is not yet handled, any thoughts on that?

**Comment by jku** [comment]
> * Importing existing keys (i.e. SSH key or YubiKey) is not yet handled, any thoughts on that?

I swear I wrote about it somewhere, but can't hurt to do it here too:
* Constructing entirely new keys or importing them is inherently specific to signing system -- we can't create generic APIs and should not try
* I would add this functionality into Signer implementations: 
   * typical use case is going to need both signer and Key at same time (to insert them into their respective storage)
   * since I've made the signer already "own" a public key in the PR, we can add generic API to get that public key from Signer
* but nothing prevents a specific Key from having a import() method as well if that makes sense for the specific use case

This fits at least the KMS use case and I think it should fit yubikeys as well.
