### ISSUE TITLE
Signer uses python2 "__metaclass__"

### ISSUE THREAD

**Issue by jku** [secure-systems-lab/securesystemslib#463]
signer.py does `__metaclass__ = abc.ABCMeta`. This is python2 syntax and does nothing. So calling `Signer()` works fine but the resulting object does not implement the Signer API (the sign method is unimplemented) 

The actually supported methods are
```python
from abc import ABC
class MyABC(ABC)
```
and
```python
from abc import ABCMeta
class MyABC(metaclass=ABCMeta)
```
the latter may be safer (WRT multiple inheritance issues)

Found in #456

**Comment by jku** [comment]
also StorageBackendInterface

**Comment by lukpueh** [comment]
This might be a bit of a digression, but I think we should be using `typing.Protocol` in most cases, where we now use `abc`. This is at least true for `Signer` and `StorageBackendInterface), where the base classes don't provide any re-usable code and we don't care if the implementations are actually subclasses of these interfaces. We just want to make sure that the implementations quack like Signers or StorageBackendInterface.

`typing.Protocol` is not in Python 3.7, but a backport exists. What do others think?

**Comment by jku** [comment]
In general I like the protocol idea for things like Signer (where the intent is to document to 3rd parties what they need to do). Caveats though:
* signer dispatch would still need to be somewhere
* anything with serialize/deserialize (like Key) seems trickier


The one  issue I have with Protocol is that the implementations never declare themselves (compare with rust Traits which you always declare with a `impl ThisTrait for ThatType`). This is very pythonic of course but it's also annoying in a very pythonic way: Does `MySpecialClass` implement the `Signer` protocol? Who knows! Go ahead and read the full source code to find out...

**Comment by joshuagl** [comment]
I agree that `typing.Protocol` seems like a good fit for our ABC's which exist only to define an interface and do not provide any base or shared functionality.
