### ISSUE TITLE
Key should expose pre hash algorithm

### ISSUE THREAD

**Issue by jku** [secure-systems-lab/securesystemslib#469]
This is after #456

There could be a optional `Key.get_pre_hash_algorithm()`:
* would return the pre-signing content hash algorithm that should be used
* this would be useful for for signers that need to prehash (KMS and HSM I believe)
* this does not apply to all keys (e.g. "ed25519" is likely the non-prehashing variant)

**Comment by lukpueh** [comment]
FYI: The HSMSigner API does not need pre-hashing. I only pre-hash in tests as workaround for SoftHSM's limited capabilities: 

https://github.com/secure-systems-lab/securesystemslib/blob/c4e3416bbe0fbe06e71449ac15ca96be7bc8a6c4/tests/test_hsm_signer.py#L22-L37

**Comment by jku** [comment]
oh interesting. If this is only needed by KMS, then we can hold off implementing anything public/generic

**Comment by jku** [comment]
I'll close this based on above comments
