### ISSUE TITLE
In tests: We can reconsider the encryption of private keys  

### ISSUE THREAD

**Issue by NabeelShahid7** [secure-systems-lab/securesystemslib#477]
Quite some time seems to be spent on decrypting private keys which can be reduced. Hence, the encryption of keys should only be done for cases that are actually testing key encryption/decryption and not for every other case.

The current runtime is around 42 seconds.

I will try to work on this.

**Comment by jku** [comment]
I think this is reasonable: there is API for encrypting, that should obviously be tested, but other key usage does not need encrypting. The other improvement area is not creating slow-to-generate keys (like rsa) if it's not needed by the test.

encryption/decryption and key generation are good guesses of time sinks but if you want to know for sure:  I've used cProfile and snakeviz to try to understand where time is actually spent: http://jiffyclub.github.io/snakeviz/
