### ISSUE TITLE
Signature verification ignores the Key ID in the signature

### ISSUE THREAD

**Issue by awwad** [secure-systems-lab/securesystemslib#51]
### Summary
`keys.verify_signature` takes a **key** and a **signature** (along with the data over which the signature may have been signed). Signature verification determines only whether or not the signature value (`sig`) can have been produced by the provided **key**. It does **not** check whether or not the signature itself reports that it was made using that key, so the keyid listed in the signature provided need not match the key in order for the signature to be deemed valid. Correct behavior, I would say, is to deem the signature invalid if the key id it lists is not the key id that is expected, without bothering to determine if the signature value ('sig') is correct.

### Example
Suppose I have two keys, k1 and k2. I use k1 to sign data, and then change the signature dictionary to claim that I used k2 by listing k2's key id, even though I signed with k1. I send you the signature. You want to know if it was generated by k1. You run `keys.verify_signature` and everything checks out, even though the signature incorrectly claims to be a signature by k2.

### Security Implications
Note that this can mean that an attacker could have a signature deemed valid without knowing what the right keyid is, and that, in upstream code, a single signature can be deemed valid if it could have been generated by any acceptable key, without the attacker having to choose one key or attempt multiple times listing different key ids. That problem depends on the behavior of upstream code, though, which can be written to eliminate that possibility.

While this may not be a **large** security issue -- the signature value itself must still match a signature produced by the provided key over the provided data -- it's confusing, may break assumptions in upstream code, and may have **some** security impact upstream (where you can use the same signature in the same signature verification request to try to match any acceptable key's signature without choosing a single key).

https://github.com/secure-systems-lab/securesystemslib/blob/433670b84f9d1490bacfcd2ba67b9ec77df0d970/securesystemslib/keys.py#L940-L946

**Comment by vladimir-v-diaz** [comment]
I agree that verify_signature() should not assume that the caller correctly matched `key_dict` with `signature`.

**Comment by vladimir-v-diaz** [comment]
I think you also noticed that a docstring is missing an exception that can potentially be raised.  Please don't forget to report this, as well.

**Comment by awwad** [comment]
The docstring bit ended up being fine. (:

**Comment by awwad** [comment]
So it turns out that while Uptane's older fork of TUF does not circumvent this issue upstream (and so has the security issue discussed until I fix it), the newest TUF code does. That is, while this is still a bug in securesystemslib, there are probably no security implications to _current_ TUF code.

**Comment by vladimir-v-diaz** [comment]
Fixed in https://github.com/secure-systems-lab/securesystemslib/pull/53.
