### ISSUE TITLE
Update README: Document  signer as first class module

### ISSUE THREAD

**Issue by jku** [secure-systems-lab/securesystemslib#511]
README should make signer module much more prominent: 
* Explain key creation, storage, signing, verification (https://theupdateframework.github.io/python-tuf/2023/01/24/securesystemslib-signer-api.html) -- only key creation happens outside the signer module
* Stop emphasizing file based keys: files are an edge case that needs to be covered but HSM and KMS are more interesting
* Explain key/signer dispatch
* Remove _Miscellaneous functions_

**Comment by lukpueh** [comment]
I'd say this can be closed via #634 and #749. We have other open docs issue, which refine the requests above.
