### ISSUE TITLE
cryptography dependency version is incorrect

### ISSUE THREAD

**Issue by jku** [secure-systems-lab/securesystemslib#600]
PR #599 bumps the dependency version. I'm planning to merge that now (to get code into a working state with documented deps) but leaving this issue open so we can still decide if we actually want to support 37: 
* the only thing we seem to use from cryptography 40 is a union type `PublicKeyTypes` that is not really that useful, not using it would be fairly easy
* if we do that we could still revert the version bump before next release

**Comment by lukpueh** [comment]
Agreed, it would easily be possible to not use `PublicKeyTypes`. I have no strong feelings here, but it seems right to ask people to use the newest version of a crypto library, which we make heavy use of.

I suggest we leave the constraint as is and reconsider lowering it if there's a need for it?
