### ISSUE TITLE
signer API: add public key attribute to Signer interface

### ISSUE THREAD

**Issue by lukpueh** [secure-systems-lab/securesystemslib#605]
Currently, the Signer interface does not prescribe the internal data structure of a signer implementation. This is because a signer is responsible for one thing only -- signing, and can be completely decoupled from private key data, and mostly decoupled from public key data.

The latter actually is part of the interface method [`from_priv_key_uri`](https://github.com/secure-systems-lab/securesystemslib/blob/5a2d43951d2be7fdb084a40cb723420bf345f54a/securesystemslib/signer/_signer.py#L168-L174), which is the canonical way of loading signers, and is usually based on information from the public key (e.g. keytype/scheme).

While signers don't necessarily require the full public key object once loaded, all current implementations [^1] do cache and use it for signing, usually to dispatch on scheme, and assign keyid to the resulting signature.

If we add the de-facto interface field `public_key: Key` indeed to the interface, signers could also be used to verify their signatures, for which use cases exist [^2].

The alternative to this proposed change would be to introduce a container format for "signer, public key"-tuples. Although, this seems unnecessary, if most signer already contain the public key.

[^1]: With the exception of `SSlibSigner`, which could easily provide an alias for `public_key` using the internal data structure, and might even become obsolete (see #604)

[^2]: `runlib.in_toto_record_stop` needs to verify preliminary link metadata, and then re-sign it.

**Comment by jku** [comment]
This makes  sense to me. 

This does mean that `from_priv_key_uri()` could have been a Signer constructor (and caller could then get `signer.public_key`). Changing this likely doesn't make sense anymore, just mentioning.

**Comment by lukpueh** [comment]
> This does mean that `from_priv_key_uri()` could have been a Signer constructor (and caller could then get `signer.public_key`). Changing this likely doesn't make sense anymore, just mentioning.

Do you mean, instead of `Signer.from_priv_key_uri(uri, public_key, secrets_handler)` it could have been `Signer(uri, public_key, secrets_handler)`?

**Comment by lukpueh** [comment]
On a related note: Any idea how to actually do this? AFAICS, Python only supports defining abstract properties not attributes. This means that Signer subclasses also need to implement `public_key` as `@property`, which does not seem so desirable.

Should we maybe just define it via docs?

**Comment by jku** [comment]
> This means that Signer subclasses also need to implement public_key as @property, which does not seem so desirable.

I think the property is probably fine -- we want `Signer.public_key` to be recognised by type checkers so there has to be something in Signer (so docs only is not great)...
