### ISSUE TITLE
update SigstoreSigner to sigstore 2.0

### ISSUE THREAD

**Issue by jku** [secure-systems-lab/securesystemslib#610]
There's a 2.0.0rc2 release for sigstore-python: we could update SigstoreSigner to the modified API and test it already

**Comment by jku** [comment]
I've got a branch. The only snag seems to be that the new API for getting the signing identity from `sigstore.oidc` fails when using ambient identities: in this case the OIDC "identity" is not the same as the signing identity (aka SAN in the signing certificate)

**Comment by lukpueh** [comment]
Done as of securesystemslib 0.30.0 https://github.com/secure-systems-lab/securesystemslib/pull/652
