### ISSUE TITLE
signer: test AWS signer with LocalStack

### ISSUE THREAD

**Issue by lukpueh** [secure-systems-lab/securesystemslib#612]
#609 adds an AWS signer including a test case (`check_aws_signer.py`), which is currently not part of our CI. @kairoaraujo suggested to try out [LocalStack](https://docs.localstack.cloud/user-guide/aws/kms/).

**Comment by lukpueh** [comment]
cc @ianhundere

**Comment by lukpueh** [comment]
Can be copied from https://github.com/repository-service-tuf/repository-service-tuf-worker/pull/452/commits/c4b26c0178ed95c3f5981cdea89863f10c8387a5

**Comment by kairoaraujo** [comment]
I will take this one

**Comment by lukpueh** [comment]
> I will take this one

I took it ... after coordinating with Kairo :) 

👉  #777
