### ISSUE TITLE
signer: Improved the "file-based signer"

### ISSUE THREAD

**Issue by lukpueh** [secure-systems-lab/securesystemslib#617]
_Originally posted by @jku in https://github.com/secure-systems-lab/securesystemslib/pull/604#discussion_r1291112824_
        

NOTE: Adopt in docs/CRYPTO_SIGNER.md (remove signer registration)

**Comment by lukpueh** [comment]
> how FileNameSigner relates to CryptoSigner

Currently, FileNameSigner subclasses CryptoSigner to make use of its `sign`, but add its own `from_priv_key_uri`. This makes sense for CryptoSigner, which is mainly characterised by its sign implementation, but could implement several different ways of accessing the private key material, e.g. from file path (CryptoSigner, SSlibSigner), file name (FileNameSigner), environment variable (SSlibSigner), etc. 

The signer API, however, is not designed to separate the two tasks and all other signers, so far, are clearly characterised by both their sign and from_priv_key_uri methods together.

For the sake of a simple consistent interface, and given that file-based signing should be an edge case, I suggest we keep CryptoSigner only and update its from_priv_key_uri to behave like FileNameSigner. This still allows applications to subclass CryptoSigner for its sign method, and implement their own from_priv_key_uri.

**Comment by jku** [comment]
this might not be ready today but I'll handle it

**Comment by lukpueh** [comment]
Addressed in #759
