### ISSUE TITLE
Feature request: Enable signing/verifying using PKCS#11

### ISSUE THREAD

**Issue by udf2457** [secure-systems-lab/securesystemslib#620]
I note there is an open request regarding Hashicorp Vault integration (#307).  However if would be useful if that effort could be expanded to include PKCS#11 (so for example, people using Yubikeys, smart cards or traditional HSMs could work with securesystemslib).

This request originates from an old [go-tuf request](https://github.com/theupdateframework/go-tuf/issues/427), but since they have `securesystemslib` as a dependency I guess it ultimately falls to you guys to (hopefully !) implement.

**Comment by jku** [comment]
securesystemslib supports PKCS#11 already and is used with Yubikeys. The docs are lacking but [HSMSigner code](https://github.com/secure-systems-lab/securesystemslib/blob/main/securesystemslib/signer/_hsm_signer.py#L75) does have an example.

...unfortunately that is unlikely to help with go-tuf as this is a python project: there's similarly named go project: https://github.com/secure-systems-lab/go-securesystemslib. Sorry for the confusing names.

**Comment by udf2457** [comment]
Ah ok, thanks @jku .  It looks like HSMSigner hasn't been ported to the go version, so I'll go open a ticket there.
