### ISSUE TITLE
support floats within _encode_canonical

### ISSUE THREAD

**Issue by chasen-bettinger** [secure-systems-lab/securesystemslib#625]
**Description of issue or feature request**:

Hi! I am implementing a new feature in the [in-toto](https://github.com/in-toto/in-toto/pull/570) python library and I encountered an issue in which, after instantiating a value for a generic struct protobuf property, a value within that object transforms from an integer into a float.

A visual:

Before the protobuf:

```json

{
  "foo": {
    "bar": 0
  }
}

```

After the protobuf:

```json
{
  "foo": {
    "bar": 0.0
  }
}
```

Following a [review of the code](https://github.com/secure-systems-lab/securesystemslib/blob/main/securesystemslib/formats.py#L634), it's possible that we could add a check for a float data type and handle it similar to how integers are being handled today: stringify the value.  Doing so would prevent [this nasty bugger](https://github.com/in-toto/in-toto/pull/570/files#diff-ee036113f348f6855448e0d706882e4863b64e087bcde592dfd30c4afc886264R36) from going any further than it already has.

What do you think?

**Comment by jku** [comment]
I think float support is unlikely:
* most importantly https://wiki.laptop.org/go/Canonical_JSON is pretty explicit so any other implementations following that "spec" would not understand our format anymore
* Deciding the "canonical representation" of a float may sound simple  but I don't think it is if you want this to be reproducible in other implementations -- maybe I'm too cynical but I expect simple stringifying to produce slightly different results on different ecosystems. Think 100 vs 100.0 vs 1e2

**Comment by chasen-bettinger** [comment]
@jku Thanks!
