### ISSUE TITLE
Release v0.29.0

### ISSUE THREAD

**Issue by MVrachev** [secure-systems-lab/securesystemslib#631]
**Description of issue or feature request**:
A new version of securesystemslib was released 4 months ago on 18-th of April.
There are many changes from then up to today:
https://github.com/secure-systems-lab/securesystemslib/compare/v0.28.0...main

**Is there anything  that stops the release @jku @lukpueh?** 

I will help the maintainers by submitting a possible `CHANGELOG` as suggested by @jku.

### Added
* Add `SigstoreKey` and `SigstoreSigner` #522.
* Add `SpxKey` and  `SpxSigner` #568.
* Add `AzureSigner` #588.
* Add `AWS KMS Signer` #609.
* Add `CryptoSigner` as a replacement for `SSLibSigner`. #604

### Changed
* Moved `spx keygen` to `securesystemslib/signer/_spx_signer.py` #568
* Use `sigstore` v. 1.1.2 #583 
* Move signature verification for "securesystemslib keys" inside `SSlibKey`. #585

### Removed
* Support for spx keygen. #568.

### Depricated
* SSlibSigner and sslib keydict #604

### Fixed
* Fix CI permission error #578

**Comment by jku** [comment]
release is a good idea.

potential blockers:
* #624, #622 
* #630 -- we should not treat this as hard blocker as the sigstore release has not happened but recent commits look like release activity :) and I'd really like to have decent sigstore support
* anything else?

**Comment by jku** [comment]
> Add SpxKey and SpxSigner https://github.com/secure-systems-lab/securesystemslib/pull/568

Hmm, the signer is not enabled by default but it's also not documented as unstable or experimental... I think it probably should: I'm thinking mostly about the key and signature container formats: they really should be documented in a TAP or something and I don't think they are currently

**Comment by jku** [comment]
I've made #632 to address the stability status

**Comment by MVrachev** [comment]
I approved it, but I am not a maintainer :D

**Comment by jku** [comment]
current blocker list
[x] #622
[x] #634
[] #632
[] #630 (soft block only: let's not block if sigstore has not released)
