### ISSUE TITLE
Does `AWSSigner.import_()` really require scheme string?

### ISSUE THREAD

**Issue by jku** [secure-systems-lab/securesystemslib#668]
I imagined there would be two good ways to implement `import_()` style methods:
* either ask caller for a key identifier and then request the key details from external service
* or ask caller for all key details

Both ways have some pros and cons.... AWSSigner seems to be half-way between these: it seems to require being logged in to AWS but still requires the user to provide a scheme string.

I would expect that the scheme is in some fashion provided in the 
 `boto3_client.get_public_key()` return value, so we could improve `import_()` so that user would not actually have to provide the scheme. Does this sound correct?

**Current behavior**:

` def import_(cls, aws_key_id: str, local_scheme: str)`

**Expected behavior**:

` def import_(cls, aws_key_id: str)`
(or maybe leave local_scheme as optional for backwards compat)

cc @ianhundere

**Comment by jku** [comment]
I think  creating the opposite of the lookup table in `_get_aws_signing_algo()` and then using that on any values in  `response['SigningAlgorithms']` should do it maybe

**Comment by lukpueh** [comment]
I mostly agree. The *aws_key_id* should determine the *keytype*, and the *keytype* determines one (ed25519, ecdsa) or multiple (rsa) eligible *schemes*.

So at least for rsa keys passing a scheme does affect the created signature. For the other keytypes it can be used to check if the key has the expected type. 

Making *local_scheme* optional does seem reasonable. We use "rsassa-pss-sha256" as default scheme elsewhere in this library, if no scheme is specified.

**Comment by lukpueh** [comment]
> We use "rsassa-pss-sha256" as default scheme elsewhere in this library, if no scheme is specified.

We currently seem to be using default schemes for ecdsa keys too, which is incorrect: https://github.com/secure-systems-lab/securesystemslib/issues/669

**Comment by ianhundere** [comment]
i'll look into this, thanks for the heads up/feedback.

**Comment by jku** [comment]
Sorry, I forgot to respond.

I don't want to give very specific or strong advice since I've never used the API -- that just seemed like a possible solution based on a quick look at the API reference.

My point was just that 
* it seems possible to make` import_()` work with just  `aws_key_id` as argument because the return value from AWS very likely includes all the required information. 
* Doing that would be good because then it would be impossible to mis-configure the key by accidentally giving the wrong scheme to `import_()`

**Comment by ianhundere** [comment]
> * it seems possible to make` import_()` work with just  `aws_key_id` as argument because the return value from AWS very likely includes all the required information.

hey @jku, so i looked into this further and i was reminded why i went with the solution that i did and it's because RSA keys have multiple `SigningAlgorithms` to choose from, so the user has to explicitly choose which scheme/padding they want to use for encryption:
```
        "SigningAlgorithms": [
            "RSASSA_PKCS1_V1_5_SHA_256",
            "RSASSA_PKCS1_V1_5_SHA_384",
            "RSASSA_PKCS1_V1_5_SHA_512",
            "RSASSA_PSS_SHA_256",
            "RSASSA_PSS_SHA_384",
            "RSASSA_PSS_SHA_512"
        ]
```

 as opposed to ECDSA whereby there is only one `SigningAlgorithms` to choose from:
```
        "SigningAlgorithms": [
            "ECDSA_SHA_256"
        ]
```

**Comment by jku** [comment]
I see. I suppose that makes sense: the hash algorithm is something that (from AWS point of view) could be different on different calls to `sign()`...

We could still choose a default at `import_()` time, right:
*  AWS docs say _When signing with RSA key pairs,  RSASSA-PSS algorithms are preferred_ and this sounds good to me
* We could just pick a hash size by default (256?)

**Comment by ianhundere** [comment]
since `rsassa-pss-sha256` is the default throughout `securesystemslib`, we could require a `local_scheme` if using RSA and sha256 is not wanted, otherwise default to `RSASSA_PSS_SHA_256`.
