### ISSUE TITLE
Remove legacy interfaces/implementation

### ISSUE THREAD

**Issue by lukpueh** [secure-systems-lab/securesystemslib#731]
The lack of a clear API in securesystemslib has been described in #270 (also see below for related issues).

The new Signer API (`secureystemslib.signer`) provides a by far more powerful replacement API for signing and verifying digital signatures.

This issue calls for the removal of legacy interfaces/implementation, in order to finalise securesystemslib's transition to the Signer API.

IMPORTANT: The removal and a subsequent release must be coordinated with securesystemslib users, most notably in-toto, python-tuf, and RSTUF. cc @adityasaky, @SantiagoTorres, @trishankatdatadog, @jku, @joshuagl, @kairoaraujo, @MVrachev.

**Modules to remove**
* keys.py
* {rsa, ecdsa, ed25519}_keys.py
* interface.py
* schema.py
* _sslib_signer.py
* settings.py

**Other**
* formats.py (remove all but `encode_canonical`)
* remove deprecated methods in SSlibKey

**Maybe revise**
* util.py (e.g. [#245](https://github.com/secure-systems-lab/securesystemslib/issues/245))
* hash.py
* storage.py (consider move to python-tuf)

closes #183,  #172 #219, #270, #280, #286, #309, #310, #367

**Comment by jku** [comment]
cc @woodruffw: This should have no effect on sigstore-python (as `encode_canonical()` remains available) but FYI.

**Comment by woodruffw** [comment]
Thanks for the heads up!

**Comment by lukpueh** [comment]
> **Maybe revise**
> 
> * hash.py
> * storage.py (consider move to python-tuf)

That's all what's left here. I suggest to move the discussion to #270 and close here.
