### ISSUE TITLE
Remove references to TUF

### ISSUE THREAD

**Issue by vladimir-v-diaz** [secure-systems-lab/securesystemslib#75]
**Description of issue or feature request**:

`securesystemslib` was not always a library. Many of its modules and functions previously lived in the [TUF repository](https://github.com/theupdateframework/tuf).  Unfortunately, there are still references to TUF in some of the `securesystemslib` comments.

**Current behavior**:
There are references to TUF in comments and there exist schemata that are only relevant to TUF.  For example:
https://github.com/secure-systems-lab/securesystemslib/blob/d1116044cfd0a9fd04077ececef9f8c148136f25/securesystemslib/formats.py#L18-L24

https://github.com/secure-systems-lab/securesystemslib/blob/d1116044cfd0a9fd04077ececef9f8c148136f25/securesystemslib/formats.py#L326-L334

**Expected behavior**:
TUF references in `securesystemslib` should be removed and TUF-related schemata relocated to the TUF repository.

**Comment by JustinCappos** [comment]
This is a low priority, cleanup item...

**Comment by lukpueh** [comment]
Fixed with #165.
