### ISSUE TITLE
Issues for KubeCon EU contribfest

### ISSUE THREAD

**Issue by lukpueh** [secure-systems-lab/securesystemslib#750]
KubeCon EU contribfest issues are labeled in the issue tracker:

https://github.com/secure-systems-lab/securesystemslib/issues?q=is%3Aissue+is%3Aopen+label%3Acontribfest

**Comment by jku** [comment]
Picking highlights from that long list of labeled items:
* #617 -- this should not be terribly difficult and this blocks good example code 
* #605 -- easy-ish, useful
* #731 -- a bit more involved but lukas has a branch already...
* #639 -- expected to be fairly simple

**Comment by lukpueh** [comment]
This issue was a landing page for contribfest-labeld during contribfest. Now that the event is over, we can close the issue.
