### ISSUE TITLE
Get a CryptographyDeprecationWarning just calling generate_ecdsa_key()

### ISSUE THREAD

**Issue by zbowling** [secure-systems-lab/securesystemslib#788]
After updating to the latest package now calling:

```python
from securesystemslib.keys import generate_ecdsa_key
key = generate_ecdsa_key()
```

Prints:
```
.... securesystemslib/ecdsa_keys.py:142: CryptographyDeprecationWarning: Curve argument must be an instance of an EllipticCurve class. Did you pass a class by mistake? This will be an exception in a future version of cryptography.
 private_key = ec.generate_private_key(ec.SECP256R1, default_backend())
```

It seems like an internal regression calling a high-level API to get that warning that looks like an internal lib issue.

**Comment by lukpueh** [comment]
Thanks for the report! `securesystemslib/ecdsa_keys.py` was recently removed in #772, so this warning won't pop up in the next release. 

There's a replacement method in [`CryptoSigner.generate_ecdsa`](https://github.com/secure-systems-lab/securesystemslib/blob/19513307625094e1b5e34885a1b0a75e84a88651/securesystemslib/signer/_crypto_signer.py#L304C9-L304C23), which you can already use, plus background info in [`CRYPTO_SIGNER.md`](https://github.com/secure-systems-lab/securesystemslib/blob/main/docs/CRYPTO_SIGNER.md)

**Comment by jku** [comment]
For background:
* cryptography 42 deprecated using class as argument
* cryptography uses a non-standard deprecation error which shows up in end user applications: It may be unfortunate for application developers but we can't really affect that
