### ISSUE TITLE
1.0 release

### ISSUE THREAD

**Issue by jku** [secure-systems-lab/securesystemslib#801]
I suppose we need an actual issue for this and not just the PR #767 .

Some possible blockers:
* docs: Remove pre 1.0  warnings (at least `signer` has one) _EDIT: done #802_
* docs: Document the Signer implementations (import methods, supported priv key urls, etc) in the reference docs #640
* docs: example app as documentation #633
* annotations: actually annotate the API, add py,typed  (see https://github.com/secure-systems-lab/securesystemslib/pull/767#issuecomment-2082169008)
* vaultsigner PR

I would say only the first one is *really* required.

**Comment by lukpueh** [comment]
> I would say only the first one is really required.

Agreed. None of above breaks the API, so we could release it in the 1.x range. Though it could happen that we discover issues that do require a major bump, while working on docs and annotations. But I think that's okay.

**Comment by lukpueh** [comment]
FYI: in-toto now also has a preparatory PR for this (https://github.com/in-toto/in-toto/pull/740). So on my end we are good to go.

**Comment by lukpueh** [comment]
There's one last minor clean-up PR, I'd like to get in before 1.0: https://github.com/secure-systems-lab/securesystemslib/pull/806
