### ISSUE TITLE
line length decision

### ISSUE THREAD

**Issue by jku** [secure-systems-lab/securesystemslib#830]
#829 moves the project to ruff linter. As a side effect we noticed we have quite a few lines that are over 80 characters long -- apparently black is more lenient in many cases. 

That PR will ignore line-too-ling (E501) to keep things moving. Let's decide what to do here:
* We can just fix the errors (either split lines or ignore whole sub modules like tests)
* or we could just use the ruff default 88 chars (and keep ignoring E501 for tests): that looks fine to me and only leaves us with half a dozen lines to fix manually

for context: There are 181 line-too-long errors (125 of them in actual sources, 56 in tests).

-- 

I think I'd be fine with ruff default line length -- it seem to be widely used in the ecosystem.

**Comment by L77H** [comment]
I would be in support for adopting the ruff default line length of 88 chars. This would reduce the number of errors from 125 to just 8 (ignoring tests) which is a quick manual fix and gives more leeway in the code style for future development.

For tests we can just ignore those with inline error suppression.

**Comment by joshuagl** [comment]
Any reason we wouldn't fix tests too if we switch the ruff default 88char?

**Comment by L77H** [comment]
Most of the lines exceeding 80 chars limit are input data strings like public keys, it could make the code more cluttered when breaking those over multiple lines to fall within 88 chars.

**Comment by joshuagl** [comment]
Thanks. The 88char default for non-test files seems like a sound approach.

**Comment by lukpueh** [comment]
> Thanks. The 88char default for non-test files seems like a sound approach.

Agreed. I don't have a strong opinion about 80 vs. 88, but I'm very much pro sane defaults and minimal diffs.

Regarding minimal diff, I'm curious, will the switch also unwrap many lines because there is more space now?

**Comment by L77H** [comment]
On first sight there are around 39 unwraps across 14 files when going from 80 to 88, excluding test files.

**Comment by lukpueh** [comment]
Okay thanks, that's still better than fixing the 125 non-test lines to fit 80. Let's do it.
