### ISSUE TITLE
linter: ruff coverage

### ISSUE THREAD

**Issue by jku** [secure-systems-lab/securesystemslib#834]
The various linters have been replaced by ruff (thanks to @L77H).

* We should have a look at the ruff rulesets and decide which are most interesting (and best value for effort): https://docs.astral.sh/ruff/rules/
* Also should look at current ignores (both noqa comments and the ignore list in pyproject) and see if we can improve code 

As a initial list, these contain useful rules
* RUF
* UP: this contains "use f-string instead of format" error which we're going to see a lot of. `flynt` tool may allow automated conversion to f-strings but we need to be very careful with that
* pylint extended rulesets PLR, PLE, PLC, PLW
* various flake rulesets: ANN at least

I have not tested how much work enabling them would be -- starting with the easiest may be a good idea

**Comment by L77H** [comment]
I tested the initial list you proposed:
- Using PL as rule includes already the following: PLR, PLE, PLC, PLW so those are already covered
- UP finds a total of 44 errors, of which most are f-string related as you already assumed
- ANN finds a total of 532 errors

I believe this is a good starting point to be added, I will create a separate PR for both UP and ANN if you agree.

**Comment by jku** [comment]
> Using PL as a rule includes the following: PLR, PLE, PLC, PLW so those are already covered

oh that makes sense -- I got tricked since pycodestyle is documented the same way but that one doesn't seem to have a "top-level" ruleset

Which reminds me: pycodestyle warnings (W) might be useful to enable as well

**Comment by L77H** [comment]
Yes the markup is a bit confusing.
Good, I will add W to the TODO list.
